### ISSUE TITLE
Add `isUserTheRepositoryCollaborator`

### ISSUE THREAD

**Issue by kidonng** [refined-github/github-url-detection#101]
I noticed there are duplicate separators for checking write access in Refined GitHub:

- https://github.com/refined-github/refined-github/blob/1fd96d7e4f50b998390562080500881c2c626c8e/source/features/quick-comment-edit.tsx#L13
- https://github.com/refined-github/refined-github/blob/1fd96d7e4f50b998390562080500881c2c626c8e/source/features/wait-for-build.tsx#L109

Maybe add a `isUserTheRepositoryCollaborator` (candidate name) method to check for the existence of `.lock-toggle-link` or `canUserEditRepo()`.

The problem is that this only works on `hasComments()`...

**Comment by fregante** [comment]
> The problem is that this only works on `hasComments()`...

`hasCommentsAndAllCanBeEditedByCurrentUserDotCom()`

**Comment by fregante** [comment]
I think these would be rather fragile, work on select pages, not tell the whole story (there are different level of "access"), and this module is mostly about URLs (pages) as the name suggests, rather than users and what they can do. We only have two, both of which are pretty straightforward as they use the Settings tab:


https://github.com/refined-github/github-url-detection/blob/dab74f6cc2c631b4cfdecc7aa11f691d90241d4f/index.ts#L701

https://github.com/refined-github/github-url-detection/blob/dab74f6cc2c631b4cfdecc7aa11f691d90241d4f/index.ts#L699
