### ISSUE TITLE
Migrate `getCurrentCommittish` and `GitHubURL` here?

### ISSUE THREAD

**Issue by kidonng** [refined-github/github-url-detection#142]
Another GitHub-related browser extension Gitako encountered the infamous "slash-in-branch-name" issue: https://github.com/EnixCoda/Gitako/issues/243

Refined GitHub had similar experience and that (along with other issues) resulted in the [`GitHubURL`](https://github.com/refined-github/refined-github/blob/3547c9bc0e60443dafe06752bc94e9e5b73f8d55/source/github-helpers/github-url.ts) helper (and its dependency `getCurrentCommittish`). I think these helpers are generally useful for others as well, so is there any interest maintaining them here?

Issue with this approach is that the helpers are huge comparing to the existing [`getRepo`](https://github.com/refined-github/github-url-detection/blob/1663cd904c179a5fbd95c008d3a54f400a02162c/index.ts#L703-L732) helper. And it's not _super_ related to URL detection, so it probably should be its own thing.

**Comment by yakov116** [comment]
I think we can extract it to be its own module, I like how simple this one is no need to complicated it.

@refined-github/maintainers thoughts?

**Comment by kidonng** [comment]
To be fair, I think most [`github-helpers`](https://github.com/refined-github/refined-github/tree/main/source/github-helpers) are useful on their own, like [`get-user-avatar`](https://github.com/refined-github/refined-github/blob/main/source/github-helpers/get-user-avatar.ts). But let's not overcomplicate things 😅 this issue only considers branch name related stuff.

**Comment by yakov116** [comment]
> maybe one day I extract them to modules myself, that's MIT for you ↩

Well be glad to host them. That's refined-github for you 🤪

**Comment by fregante** [comment]
Link: https://github.com/KSH-code/refined-github/blob/59ca79f8ad477df9417eb56919b0a674a5b54fe4/source/github-helpers/index.ts#L21

Things I'm not excited about:

- how transient and imperfect each of those API is
- documenting them and releasing breaking versions more often than this module requires
- external contributions (or [lack thereof](https://github.com/refined-github/github-url-detection/pulls?q=is%3Apr+is%3Aclosed+-author%3Afregante+-author%3Akidonng+-author%3Ayakov116+
))
- the slowing of RG’s development due to having them externally and having to consider third parties
- having to also extract every internal function that those helpers use, further slowing RG’s development

I wouldn't be totally opposed to publishing a "gh extensions utils" package but I'd probably suggest using `npm install refined-github/refined-github` in order to access those files directly instead.

**Comment by fregante** [comment]
I'll add, even if we go to the trouble of doing all of that, it doesn't mean it actually helps that many people. See how many repos use this very simple, very old package:

https://github.com/refined-github/github-url-detection/network/dependents

Here's the total of 2 non-fork non-ghosttown extensions that use it:

- https://github.com/ineo6/git-master/search?q=github-url-detection
- https://github.com/hypertrons/hypertrons-crx/search?q=github-url-detection

I'd argue we didn't even need to extract `github-url-detection`. 😃 The only reason it's still great to have is that it makes it easier to test it and work on it.

**Comment by yakov116** [comment]
> The only reason it's still great to have is that it makes it easier to test it and work on it.

Exactly why we extracted, the tests took too much time.

**Comment by kidonng** [comment]
@fregante Really good points. I agree it's too much hassle for those simple helpers, I brought up about this one because I think it's an exception:

- There are projects that could benefit from it
- It (mostly) fits in this package
- More people using it, more bugs found

**Comment by fregante** [comment]
PR welcome to add those two:

- utils/github-url.ts
- utils/get-current-committish.ts
